---
# git tasks file for common

- name: Set Git username
  become: yes
  become_user: "{{ user }}"
  ansible.builtin.command:
    cmd: "{{ item }}"
  with_items:
    - git config --global user.name "{{ git_user_name }}"
    - git config --global email.address "{{ git_user_email }}"

- name: Clone public GitHub repositories
  become: yes
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: https://github.com/{{ git_user_name }}/{{ item }}.git
    #repo: git@github.com:{{ git_user_name }}/{{ item }}.git
    dest: ~/development/{{ item }}
    clone: yes
  with_items: "{{ git_public_repos }}"

#- name: Clone private GitHub repositories
#  become: yes
#  become_user: "{{ user }}"
#  ansible.builtin.git:
#    repo: https://github.com/{{ git_user_name }}/{{ item }}.git
    #repo: git@github.com:{{ git_user_name }}/{{ item }}.git
#    dest: ~/development/{{ item }}
#    clone: yes
#  with_items: "{{ git_private_repos }}"

#- name: Create symbolic links to Git repositories
#  become: yes
#  become_user: "{{ user }}"
#  ansible.builtin.file:
#    src: '{{ home_dir }}/{{ user }}/{{ dirs[0] }}/{{ git_public_repos [1] }}'
#    dest: '{{ home_dir}}/{{ user }}/{{ dirs[1] }}/{{ git_public_repos [1] }}'
#    state: link

- name: Create symbolic links to Git directories
  become: yes
  become_user: "{{ user }}"
  ansible.builtin.file:
    src: '{{ home_dir }}/{{ user }}/{{ dirs[0] }}/{{ item.path }}'
    dest: '{{ home_dir }}/{{ user }}/{{ item.dest }}'
    state: link
  with_items:
    - { path: "{{ git_public_repos[0] }}", dest: "{{ dirs[1] }}/ansible_link" }
    - { path: "{{ git_public_repos[1] }}", dest: "{{ dirs[2] }}/home_page" }
    - { path: "{{ git_public_repos[1] }}", dest: "{{ dirs [2] }}/home_page_02" }