---
# tasks file for common

- name: Setup tasks
  include_tasks: setup.yml

- name: Fedora tasks
  include_tasks: fedora.yml
  when: ansible_facts['distribution'] == "Fedora"

- name: Git configuration tasks
  include_tasks: git.yml

- name: KVM configuration tasks
  include_tasks: kvm.yml

- name: User configuration tasks
  include_tasks: user_config.yml

- name: Appearance tasks
  include_tasks: xfce_setup.yml