---
# tasks file for common

- name: Create directories
  become: yes
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: '{{ home_dir }}/{{ user }}/{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - "{{ dirs }}"

- name: Tasks for Fedora
  include_tasks: fedora.yml
  when: ansible_facts['distribution'] == "Fedora"

- name: Tasks for Git configurations
  include_tasks: git.yml

#- name: Tasks for KVM configurations
#  include_tasks: kvm.yml

- name: Tasks for user configurations
  include_tasks: user_config.yml