---
# setup tasks file for common

- name: Remove stock user-dirs.defaults file
  ansible.builtin.file:
    path: /etc/xdg/user-dirs.defaults
    state: absent

- name: Add updated user-dirs.defaults file
  become: true
  ansible.builtin.copy:
    src: ../files/user-dirs.defaults
    dest: /etc/xdg/user-dirs.defaults
    owner: root
    group: root
    mode: '0644'

- name: Remove user-dirs file in local config
  ansible.builtin.file:
    path: '{{ home_dir }}/{{ user }}/.config/user-dirs.dirs'
    state: absent

- name: Remove residual directories
  ansible.builtin.file:
    path: '{{ home_dir }}/{{ user }}/{{ item }}'
    state: absent
  with_items:
    - "{{ residual_dirs }}"

- name: Create directories
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: '{{ home_dir }}/{{ user }}/{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - "{{ dirs }}"

- name: Copy display scripts for use with arandr
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: ../files/{{ item }}
    dest: "{{ home_dir }}/{{ user }}/{{ dirs[2] }}"
    mode: '700'
  with_items:
    - docked.sh
    - undocked.sh