---

# task file to configure git

- name: Configure the git username on asset
  git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"
  tags:
    - git

- name: Configure the git email address on asset
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
  tags:
    - git

- name: Clone remote repositories from GitHub to local drive
  become_user: "{{ user }}"
  git:
    repo: "{{ github_page }}/{{ git_username}}/{{ item.repo }}.git"
    dest: "{{ item.dest }}"
    clone: yes
  with_items:
    - { dest: "{{ git_repo_dest }}/ansible", repo: ansible }
    - { dest: "{{ git_repo_dest }}/blog", repo: dennis-perrone.github.io }
    - { dest: "{{ git_repo_dest }}/welcome", repo: dennis-perrone }
    - { dest: "{{ git_repo_dest }}/scripts", repo: scripts }
  tags:
    - git
    