---
# tasks file for common

- name: Run distribution specific playbook [arch]
  include_role:
    name: arch
    apply:
      tags:
        - arch_baseline
        - arch_gnome
        - arch_workflow
  when: ansible_facts['distribution'] == "ArchLinux"

- name: Run distribution specific playbook [centos]
  include_role:
    name: centos
    apply:
      tags:
        - centos_baseline
        - centos_gnome
        - centos_workflow
  when: ansible_facts['distribution'] == "CentOS"

- name: Run distribution specific playbook [fedora]
  include_role:
    name: fedora
    apply:
      tags:
        - fedora_baseline
        - fedora_gnome
        - fedora_workflow
  when: ansible_facts['distribution'] == "Fedora"

- name: Run distribution specific playbook [ubuntu]
  include_role:
    name: ubuntu
    apply:
      tags:
        - ubuntu_baseline
        - ubuntu_gnome
        - ubuntu_workflow
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Run distribution agnostic configurations
  include: "{{ item }}"
  with_items:
    - "git.yml"
